### ISSUE TITLE
Posibles errores

### ISSUE THREAD

**Issue by Petemir** [CubaWiki/Proba-resumen-ffrizzo#1]
Hola, usé en parte este resumen para dar el final hace unos meses, antes que nada, ¡muchas gracias!

Hice unas anotaciones a mi PDF de lo que considero que son errores, ya sea porque no les encontré sentido o porque difiere del apunte original de las profesoras. Si bien podría mandarme a corregirlo yo, prefiero escribirlas acá para asegurarnos de estar todos de acuerdo. Si coincidimos en que son errores no tengo problema en hacer las correcciones.
- Página 5: en el comienzo de la página, donde se encuentra la demostración del Teorema de Probabilidad Total, dice B unión S, pero debería ser intersección (lo mismo en la segunda igualdad, cuando se reemplaza S por su partición).
- Página 19: en la tabla de las funciones generadoras de momentos, están mal las de Poisson y la Normal. La de Poisson es `e^(l*(e^t -1))` (l es lambda; el resumen dice `e*l*(e^t-1))`; la Normal es `+u*t` (u es mu; el resumen dice `s*t`, siendo s sigma).
- Página 21: esta es una corrección relativamente menor. En la definición de funciones de densidad marginal, en particular la de Y, aparece x como parámetro, y debería ser y.
- Página 29: esto ya no sabría cómo catalogarlo ni cuál es la respuesta. En el apunte de las profesoras, se define Chebyshev con una desigualdad estricta, pero no se usa la desigualdad de Márkov como demostración. En el resumen, se utiliza Márkov, que sí se define con un mayor o igual. Tal vez no incida cuando se ve sobre V.A. continuas., pero supongo que sí con V.A. discretas...
- Página 30: mismo caso que para el anterior, pero con la Ley de los Grandes Números. En el apunte de las profesoras dice >, acá >=.

Saludos y gracias una vez más!

**Comment by FlyingPumba** [comment]
@Petemir gracias a vos por tomarte el tiempo de comentar estos errores !
- Página 5: Sip, ahí vá una intersección en la primera y segunda desigualdad.
- Página 19: Correcto
- Página 21: :+1:
- Página 29: Estuve leyendo otras fuentes y parece ser que es una desigualdad no estricta (o sea, estaría bien con menor igual). Más allá de eso, veo que en el resumen hay una demo para el caso continuo.
- Página 30: En este caso creo que es estricta la desigualdad, y así está anotado en la página 29. Igualmente en la demo de la página 30 me parece que está bien que lleve menor igual, porque está usando la desigualdad de Chebyshev. En [Wikipedia](https://en.wikipedia.org/wiki/Law_of_large_numbers#Proof_using_Chebyshev.27s_inequality) lo demuestran de esa forma. Quizas se podría reescribir para que quede mejor.

Si querés hacer las correcciones no hay problema, sino lo trato de hacer yo el finde.
Saludos.

**Comment by Petemir** [comment]
Bueno, ahí hice las correcciones de los primeros 3 puntos, los últimos 2 se me escapan. No deben estar mal entonces, simplemente no coincide el apunte de las profesoras con Wikipedia ni el resumen, pero deben ser todas válidas.

**Comment by francofrizzo** [comment]
Chicos, antes que nada gracias por las correcciones. @Petemir, me alegro que el apunte te haya sido útil.

En cuanto a lo de la página 29 (Chebyshev), incluí la demostración basada en Márkov porque fue la forma en la que se había hecho en clase, y me pareció una demostración más clara que la del apunte de las profesoras (que además solo contemplaba el caso continuo). De todas formas incluí esa como demostración alternativa. La demostración del apunte está basada en el libro "A First Course in Probability" de Sheldon Ross (el mismo que cito en la parte de cadenas de Márkov), pág. 388, y ahí la desigualdad aparece como no estricta. Creo que de todas formas no habría problema para probar la desigualdad estricta modificando de la misma forma la desigualdad de Márkov. Como sea, por ahí podríamos considerar agregar una nota aclaratoria al pie.

Con la LGN pasa lo mismo: en el libro de Ross aparece como no estricta y en el apunte de las profesoras como estricta, lo cual tiene sentido porque en ambos casos lo prueban usando Chebyshev. Sugiero que cambiemos la definición de convergencia en probabilidad de la página 29 para que todo quede consistente, no sé si les parece bien.

Otro detalle: justo después, pasa exactamente lo mismo con la versión Bernoulli de la LGN. Habría que hacer estricta la desigualdad ahí también.

Gracias de nuevo por la ayuda. Saludos.

**Comment by tcaballero** [comment]
Buenas! Estoy siguiendo el apunte junto con el original (de Bianco-Martinez) y encontré un pequeño error en la _página 28_, primer corolario: Cuando se define la igualdad de la varianza, en este caso, no debe estar al cuadrado. En el apunte de Bianco figura como "sigma" cuadrado, es decir la varianza. 
Un saludo y gracias!

**Comment by francofrizzo** [comment]
¡Gracias! Lo acabo de arreglar. Un saludo :)
